package OOPConcepts.Composition1;


/*

                                                            COMPOSITION

DEFINITION: COMPOSITION IT'S A CONCEPT IN OOP WHERE THERE IS A RELATION BETWEEN OBJECTS, WHERE ONE OBJECT IT IS COMPOSED
BY OTHER OBJECTS, THIS RELATION IT'S DESCRIBED AS "HAS-A" RELATED TO OBJECTS

SO A CONTAINER CLASS IT IS COMPOSED BY ONE OR MORE INSTANCES OF OTHER CLASSES (COMPONENT CLASSES). COMPONENTS CAN'T EXIST
INDEPENDENTLY OF CONTAINER, IF IT'S GET DESTROY, ALSO COMPONENTS ALSO WILL. IN THIS EXAMPLE, THE DEPENDENCY OF A POWER
SUPPLY FOR A MOTHER BOARD IT MAKES SENSE, BECAUSE A MOTHER BOARD CAN'T WORK WITHOUT A POWER SUPPLY
 */
public class Main {
    public static void main(String[] args) {

      MotherBoard mothBordA = new MotherBoard("Intel",40.30,"MB-RXZ79","PowerS23","Corsair",29.70);
      mothBordA.showDetails();

    }
}
